// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgsxetegsktjwflvgdrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhnc3hldGVnc2t0andmbHZnZHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODIxOTQsImV4cCI6MjA3Mzk1ODE5NH0.0JpAgy_Rtmgc_1E-oHD6y9Qt2IL_ULrXP9MTA-yhFhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});